### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by spodermenpls** [da2x/fluxfonts#6]
The idea behind Fluxfonts is great, unfortunately us "mainstream" Windows users are not able to use it and there are no equivalent programs available to my knowledge. You wrote that "Windows is unsupported at this time.", is a port planned in the future? How much effort do you think would it take to port it to Windows?

**Comment by da2x** [comment]
You’re the first to ask for it.

I had a look at it now, and it looks like  it would be a lot of work to rewrite for Windows. Fluxfonts is too dependent on POSIX libraries. I’ll have another look at it next week.

**Comment by spodermenpls** [comment]
Maybe Fluxfonts just hasn’t reached enough mainstream popularity yet? 😅 For example, on browserleaks.com/fonts your program isn’t cited as an possible anti-venom..

Considering the number of fonts on most clients never changes and is therefore the best fingerprinting item there is, it would be great to make it accessible to the Windows audience since there are no alternatives available, except maybe for installing and deleting fonts every hour by hand.

**Comment by fastitua** [comment]
da2x, how long wait on windows?)

**Comment by da2x** [comment]
Quite a while considering that I’d have to rewrite it from scratch and that I’ve had only two requests for it in 4 years … . 

It can run in the Windows Subsystem for Linux. All it requires to be picked up by Windows when running inside Windows Subsystem for Linux are these two commands:

    mkdir /mnt/c/Windows/Fonts/Linux-fonts/
    ln -s /usr/share/fonts/ /mnt/c/Windows/Fonts/Linux-fonts/

You can install WSL in Windows 10 by going to start and searching for `Optional Features`. Install WSL from the list. Then open `Bash for Ubuntu for Windows` from the Start menu.

**Comment by fastitua** [comment]
Thanks for your reply!
But i don't can understand, i can use in windows os or not? 
maybe, u have plugin for mozilla? this is very best variant and our people want this plugin or soft on windows)

**Comment by da2x** [comment]
You can run Fluxfont in Windows 10 inside the Windows Subsystem for Linux (WSL). It’s a compatibility layer that lets you run Linux software on Windows. Look it up on the web for more details.

It can’t be turned in to a browser plugin because the browsers and their plugin environments are way too limited to handle this. It has to run on native code (good old traditional software). Currently, the native code is only written for Linux, macOS, FreeBSD, and other “UNIX-like operating systems”. 

Rewriting Fluxfonts to work on Windows as an executable would take me ten days of work. I’m not really all that interested in doing this work for free at this time. You can do it yourself (this is an open source project), or you can pay someone else to do it, or you [add an open bounty](https://www.bountysource.com/issues/39556582-windows-support) (crowd funding) on it.

**Comment by spodermenpls** [comment]
@fastitua Would you like to contribute to the bounty as well? I would be willing to pay a majority of the 120 $ set by @da2x, but not all of it by myself.

**Comment by da2x** [comment]
Looks like you guys can get a prototype sometime next week. Needs to be started manually to create fonts, and the fonts will have to be deleted manually.

I spent my Saturday porting the code. I have something that can generate fonts now, but the generated fonts are slightly broken. I still need to rewrite the font manager and scheduler, make an installer, and then I need to make sure this kind of manipulation in the font store won’t create software compatibility problems. Not sure anyone has ever auto-installed and uninstalled hundreds of fonts per day on Windows before. Not even sure where to start testing that. Oh, yeah — and I’ll need to test that macOS, Linux, and FreeBSD still work.

Looks like it will run on Windows 10 only. Targeting Windows 7+8+10 would add two–three days of work while Windows 10 let me recycle much more of the existing code.

**Comment by spodermenpls** [comment]
Sounds great! I would gladly cover the testing part, I run Windows 10 and many different software suites to test with and I’ve got a lot of spare time on hand right now.

Now that you were able to re-use a good chunk of the existing code (and evaporate your 10 days of work estimate), would you be willing to cut down your set goal of 120 $? There might be a good chance that I’m the only one willing to support your porting work financially. I would be willing to grab deep down my wallet to blur that last blatant fingerprint item on my system, but not that deep. 😅

Since I don’t use Windows versions earlier than 10 anymore, I’d have no problem with Fluxfonts only being compatible with Win 10.

**Comment by da2x** [comment]
There is no obligation to pay anything. The set goal is equal to one day’s pay, even though I expect to use more, but any bounty is paid when this issue is closed. If this work is worth anything to you, then you may put funds towards the bounty if you choose.

**Comment by spodermenpls** [comment]
I’ve just donated 60 $ for your work. 😉

**Comment by da2x** [comment]
Testing notes:

1. Download and run the test executable (nothing at all will happen except for maybe a UAC confirmation). Only start it once; there is no singleton lock in place.
2. Check that it is indeed running in the Task Manager.
3. Open 32-bit registry (`%SYSTEMROOT%\SysWOW64\regedt32.exe`) and look for oddly named `.otf` fonts in `\\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Fonts`.
4. Keep an eye on this registry key, and make sure fonts are removed and added every 20 minutes or so. (Press F5.) The number of fonts will be anywhere from 1 to 6. If you see more than 6 after running it for a while, then there is a problem.
5. Open as many programs as you can and check that strangely named (or apparently invisibly named) fonts appear. You may need to relaunch the program every 20 minutes for changes to appear. Pretty much any behavior is acceptable when you select one of these fonts from the UI except crashes, warnings, or other signs of trouble. Invisible text, garbled text, or anything like that is fine. Though I expect you’ll actually see your default font and everything will appear to be working.
6. Keep an eye on memory in Task Manager: Details _for a day or two_. Physical memory should be very stable. Only really expected to grow once 4–20 minutes after you start it.
7. Linux, macOS, FreeBSD, and Raspbian (armv7) should continue to work like before.

Notes for remaining work:

* Add win32 singleton lock.
* Quadruple-check `RegDeleteValueA`. What are allowed `lpValueName` values?
* Installer or self-executing magical unicorn? Unicorn.
* Service or task scheduler? Task Scheduler if manageable from unicorn.
* Fix goddamned whitespace mess introduced by VS17. Embracing `clang-format` would do the trick.
* Reevaluate whether VS17+cang is an utterly insane requirement for building or not. (It is, but also so much closer to posix c-compilers.)
* USC2be encoder may be producing USC2le on armv7 because I’m a terrible programmer and shouldn’t have written a custom encoder.

**Comment by spodermenpls** [comment]
Do you think there will be differences depending on if it’s run on a 32 or 64 bit system (which I and the majority of users these days use)?

**Comment by da2x** [comment]
> Do you think there will be differences depending on if it’s run on a 32 or 64 bit system (which I and the majority of users these days use)?

Not to end users, no.

**Comment by da2x** [comment]
Commits 176c865, 4170151, b6afa79, 9ff19b7, and 2091a4f.

**Comment by da2x** [comment]
Test-version from commit 2091a4f.
https://1drv.ms/u/s!AnG3GZhksKxwg4cALhL_AhFi8Wk7fg

1. Run the installer
2. See above test notes

**Comment by Gitoffthelawn** [comment]
> Looks like it will run on Windows 10 only. Targeting Windows 7+8+10 would add two–three days of work while Windows 10 let me recycle much more of the existing code.

Having it run on Windows 7 and/or 8/8.1 would be great.  But given the time required, I certainly don't have any expectation.  I just wanted to let you know it will be great if you are able to do it.

**Comment by da2x** [comment]
> Having it run on Windows 7 and/or 8/8.1 would be great. But given the time required, I certainly don't have any expectation. I just wanted to let you know it will be great if you are able to do it.o.

Windows 7 may be the largest operating system in the world with a hefty margin. Microsoft’s failure at updating their user-base aside, it’s also a 7 years old operating system. Patches to make Fluxfonts compatible with 7, 8, and 8.1 are welcome but I’ll not spend any time to support these old operating systems.

**Comment by spodermenpls** [comment]
I’ve tested it for a couple of hours now. 
The RAM consumption started at 695 KB and decreased gradually to 544 KB towards the end of the test run. In the list of installed fonts, there were never more than 6 new fonts at a time, even though the font list keeps piling up when you check it with the Flash Player readout at https://browserleaks.com/fonts (started at 440, now at 496) and with e.g. Word 2010 and Photoshop CS5, old fonts don’t vanish reliably and keep staying in the list. If chosen a fake font to write with, the programs switch to another (legit) font, it doesn’t produce problems. 
Is it possible to make the program only delete fonts, when it creates new ones next? I saw long periods of time in which no fake fonts were shown in the fonts list (exposing the real number of fonts) and giving me the impression that Fluxfonts maybe has stopped working.
Do you think it makes a difference if I run Fluxfonts with administrator rights or without?

**Comment by da2x** [comment]
> In the list of installed fonts, there were never more than 6 new fonts at a time, even though the font list keeps piling up when you check it with the Flash Player readout.

Flash Player will cache installed fonts for the duration of its session. Not really causing any problems. Closing the tab in the browser (or otherwise ending the pluginhelper task) should reset it. Does the number persist when you restart all your browsers?

> Is it possible to make the program only delete fonts, when it creates new ones next? I saw long periods of time in which no fake fonts were shown in the fonts list (exposing the real number of fonts) and giving me the impression that Fluxfonts maybe has stopped working.

That is how it works. However, you can end up with no fluxfont fonts when you randomly get a naming collision with an installed system font and fluxfont has randomly decided to only make one font at the same time. The odds of that ever happening are astronomical.

What is more likely is that the font was indeed installed correctly, but that you ran into issue #7. I don’t understand exactly what causes that issue – although I’m fairly sure it’s a race condition internally in Windows and that it has nothing to do with Fluxfonts. I’ve triggered it manually when installing a dozen or so of actual fonts file to test.

>  Do you think it makes a difference if Fluxfonts is run with administrator rights or without?

You can’t run it without admin rights. Windows doesn’t have granular permissions, and you need admin rights to write to `%SYSTEMROOT%\Foots`.

**Comment by Gitoffthelawn** [comment]
> Windows 7 may be the largest operating system in the world with a hefty margin. Microsoft’s failure at updating their user-base aside, it’s also a 7 years old operating system. Patches to make Fluxfonts compatible with 7, 8, and 8.1 are welcome but I’ll not spend any time to support these old operating systems. 

No problem.  I understand.  Do keep in mind that Windows 7 and 8 (now 8.1) have been updated extensively since their releases.  By comparison, Linux is technically a 25 year old operating system.  Of course, it has received many updates and patches as well.

**Comment by spodermenpls** [comment]
> Flash Player will cache installed fonts for the duration of its session. Does the number persist when you restart all your browsers?

The problem was that fonts were only deleted in Windows’ font lists, not in the programs’ (Flash Player, Word, Photoshop) lists. By restarting my system all the lists were cleared off again, that fonts are piling up in the cache (after a couple of days probably in the hundreds) is still not the best solution though.
You mentioned that FontCache locks the fonts from deletion sometimes, do you think there could be something done to solve it (or only by Microsoft)? I found 9 font corpses in the Fonts file by using a third party file manager (corpses are not displayed in the system), but are not able to delete them. Probably only possible by using a Live Linux on my USB stick.. the deletion mechanism is still dissatisfying.

**Comment by da2x** [comment]
> not in the programs’ (Flash Player, Word, Photoshop)

Thee programs have custom font rendering and [glyph] caching engines. It’s up to them to invalidate deleted fonts and cache new fonts.

> You mentioned that FontCache locks the fonts from deletion sometimes

Resolved in #7. The service was so eager that it didn’t always wait for the file write to finish before reading it, resolved by locking the file. Tested it a million times (literally) and seems to work.

> file corpses

The problem is that FontCache doesn’t release its lock on these files. Possibly fixed in #7 as well.

**Comment by spodermenpls** [comment]
OK, thanks for the info. Can you refesh the installer on OneDrive, so I can try the new fix?

**Comment by da2x** [comment]
Here you go. Contains more aggressive deletion for Windows too.
https://1drv.ms/u/s!AnG3GZhksKxwg4cBTele39cmbf946w

**Comment by spodermenpls** [comment]
Well, I am testing right now and unfortunately it did not solve the font corpse problem and the failing "slower cycle while on battery" function. Do you have new ideas up your sleeve that could solve these issues? 😅

For a little impression I attach a screenshot with the font folder after the re-install: http://www.bilder-upload.eu/upload/034b7b-1488588533.jpg (3 corpses again, not visible elsewhere, not deletable without Live Linux)

**Comment by da2x** [comment]
> slower cycle while on battery

I don’t intend to support it on Windows. It’s actually entirely pointless on any platform, and is just in the product as I was playing with the APIs at the time. :) Opening the Start menu probably consume a lot more power than a fluxfonts cycle.

> 3 corpses again, not visible elsewhere, not deletable without Live Linux

The file is indeed deleted. The eccentricities of win32 and NTFS aside, the worst case scenario is now that the font [is deleted when you reboot](https://github.com/da2x/fluxfonts/blob/4bbe904/lib/utils.c#L332-L340). There is only so much I can do when the platform doesn’t do as it’s told. I can’t release the exclusive locks other processes arbitrarily put on files without undiscriminating killing those other processes. It would be a very unproductive massacre.

**Comment by spodermenpls** [comment]
I doubted the API was working for Windows all along, thanks for the info.

The registry entries are indeed deleted, but not the cited files in the fonts folder. Windows seems to forget to  delete them when the system is re-booting or coming out of standby mode. The little font graveyard piling up won’t effect the system’s performance though, so it’s not very tragic. It would be nice nevertheless, if Windows was cleaning its act up automatically, instead of me doing the clean up manually by using "backdoor access" through my USB stick Linux, because the files are locked from being deleted while Windows is running..

Thank you very much for investing your time to create this port!
